---

- name: Common tasks
  hosts: all
  remote_user: centos
  become: yes
  become_method: sudo
  vars_files:
    - "group_vars/all.yml"

  roles:
    - epel
  tasks:
    - include: tasks/global_task.yml